export const BloodAvailableTableTempData = [
    {
      id: 1,
      donorName: "John Doe",
      bloodType: "O+",
      date: "Aug 15, 2022",
      location: "New York",
      contact: "9435093881",
    },
    {
      id: 2,
      donorName: "Jane Smith",
      bloodType: "A-",
      date: "Aug 15, 2022",
      location: "Los Angeles",
      contact: "8133294228",
    },
    {
      id: 3,
      donorName: "Michael Johnson",
      bloodType: "B+",
      date: "Aug 15, 2022",
      location: "Chicago",
      contact: "8133294228",
    },
    {
      id: 4,
      donorName: "Emily Davis",
      bloodType: "AB-",
      date: "Aug 15, 2022",
      location: "Houston",
      contact: "8133294228",
    },
    {
      id: 5,
      donorName: "David Wilson",
      bloodType: "O+",
      date: "Aug 15, 2022",
      location: "Miami",
      contact: "8133294228",
    },
    {
      id: 6,
      donorName: "Sophia Taylor",
      bloodType: "A-",
      date: "Aug 15, 2022",
      location: "San Francisco",
      contact: "8133294228",
    },
    {
      id: 7,
      donorName: "James Anderson",
      bloodType: "B+",
      date: "Aug 15, 2022",
      location: "Seattle",
      contact: "8133294228",
    },
    {
      id: 8,
      donorName: "Olivia Brown",
      bloodType: "AB-",
      date: "Aug 15, 2022",
      location: "Boston",
      contact: "8133294228",
      
    },
    {
      id: 9,
      donorName: "William Thomas",
      bloodType: "O+",
      date: "Aug 15, 2022",
      location: "Dallas",
      contact: "8133294228",
    },
    {
      id: 10,
      donorName: "Ava Lee",
      bloodType: "A-",
      date: "Aug 15, 2022",
      location: "Atlanta",
      contact: "8133294228",
    },
  ];
  