# Generated by Django 4.1.9 on 2023-05-28 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userIdEmail', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=50)),
                ('payement', models.CharField(max_length=50)),
                ('delivery', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
