# Generated by Django 4.1.9 on 2023-06-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedb',
            name='category',
            field=models.CharField(default='Not Defined', max_length=50),
        ),
    ]
