# Generated by Django 4.1.9 on 2023-06-22 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesApi', '0003_alter_invoicedb_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodUnitsDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('bloodType', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('unitsAvailable', models.CharField(max_length=5)),
            ],
        ),
    ]
