# Generated by Django 4.1.9 on 2023-06-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesApi', '0004_bloodunitsdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodUnitsDB',
            new_name='BloodDB',
        ),
    ]
