# Generated by Django 4.1.9 on 2023-06-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesApi', '0005_rename_bloodunitsdb_blooddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddb',
            name='userIdEmail',
            field=models.EmailField(default='not set', max_length=254),
            preserve_default=False,
        ),
    ]
