# Generated by Django 4.1.9 on 2023-06-22 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankMembersDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userIdEmail', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('organization', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('operatingCity', models.CharField(max_length=50)),
            ],
        ),
    ]
